version: "3"
services:
 sychugovka-netology-db:
  image: postgres:latest
  container_name: sychugovka-netology-db
  ports:
   - 5432:5432
  volumes:
   - ./pg_data:/var/lib/postgresql/data/pgdata
  environment:
    POSTGRES_PASSWORD: sychugovka12!3!!
    POSTGRES_DB: sychugovka_db
    PGDATA: /var/lib/postgresql/data/pgdata

  networks:
   sychugovka-my-netology-hw:
    ipv4_address: 172.22.0.2
  restart: always
